#!/bin/bash

# ZYV
#
# For all repos and all arches...
#
for i in `find . -mindepth 2 -maxdepth 2 -type d ! -name pypi`; do
    if [ "$i" != "." ]; then
        createrepo $i
    fi
done

# Set the right SELinux context
#
chcon -Rh --reference /var/www/html .
